kernel_source(crypto_free.c)
kernel_source(crypto_malloc.c)
kernel_source(crypto_util.c)
kernel_source(crypto_zeroize.c)

kernel_subdirectory(cipher)
kernel_subdirectory(hash)
kernel_subdirectory(mpint)
kernel_subdirectory(prng)
kernel_subdirectory(test)
